server:
  port: 8080
spring:
  cloud:
    consul:
      enabled: true
      host: 114.215.173.71
      port: 8500
      discovery:
        enabled: true
        instance-id: ${spring.application.name}-${random.uuid}
debug: true