server:
  port: 6010
spring:
  cloud:
    consul:
      enabled: true
      host: localhost
      port: 8500
      discovery:
        enabled: true
        instance-id: ${spring.application.name}-${random.uuid}
debug: true