server:
  port: 8885
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8881/eureka/

zuul:
  routes:
    ribbonServer:
      path: /ribbon/**
      serviceId: consumer-ribbon
    feignServer:
      path: /feign/**
      serviceId: consumer-feign
spring:
  application:
    name: zuul-gateway