server:
  port: 8881

# 单节点EurekaServe配置
eureka:
  instance:
    hostname: localhost
  #    prefer-ip-address: true # 使用ip
  #    lease-renewal-interval-in-seconds: 30 # 服务续约任务的调用时间间隔
  #    lease-expiration-duration-in-seconds: 90  # 服务失效时间
  server:
    enable-self-preservation: false
  #    eviction-interval-timer-in-ms:
  client:
    register-with-eureka: false # 不向注册中心注册自己
    fetch-registry: false       # 并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
debug: true

