server:
  port: 6666
spring:
  application:
    name: config-server
  rabbitmq:
    addresses: localhost
    username: futao
    password: 123456
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FutaoSmile/SpringCloudConfigRepostory # 配置git仓库地址
          search-paths: respo       # 配置仓库路径
      label: master           # 配置仓库的分支
  config:
    name: config-server
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"